#!/bin/bash

if [ $# -ne 0 ]; then
    echo "Usage: path/to/cc/apt-setup"
    echo
    echo "Install all build prerequisites."
    exit 1
fi

if [ "$(command -v apt)" == "" ]; then
    echo "Could not find the APT package manager."
    echo "This tool works only on Debian style systems."
    exit 2
fi

if [ "$CCBUILD" == "" ]; then
    CCBUILD=$(command -v ccbuild)
fi

if [ "$CCBUILD" == "" ]; then
    echo "Could not find 'ccbuild' executable."
    echo "Make sure \$PATH or \$CCBUILD points to ccbuild."
    exit 4
fi

if [ "$(command -v apt-file)" == "" ]; then
    set -o verbose
    sudo apt-get install apt-file
    sudo apt-file update
    set +o verbose
fi

PACKAGES=""
CMD="$CCBUILD -configure-list $(dirname $0)"
echo $CMD
for name in $($CMD); do
    CMD="apt-file search -l pkgconfig/$name.pc"
    echo $CMD
    P=$($CMD)
    PACKAGES="$PACKAGES $P";
done

CMD="sudo apt-get install $PACKAGES"
echo $CMD
$CMD
