#!/bin/sh

if [ $# -ne 0 ]; then
	echo "Usage: path/to/FTL/bootstrap"
	echo
	echo "Bootstraps the FTL library's build system (Mach)."
	exit 0
fi

if [ -f $PWD/Recipe ]; then
	echo "I'd like to be called out-of-source."
	exit 1
fi

$(dirname $0)/mach/bootstrap $(dirname $0)
