#!/bin/sh

if [ $# -ne 0 ]; then
    echo "Usage: path/to/cc/bootstrap"
    echo
    echo "Bootstraps the build system (ccbuild)."
    exit 1
fi

if [ -f $PWD/Recipe ]; then
    echo "I'd like to be called out-of-source."
    exit 1
fi

if uname -o|grep Cygwin; then
    BOOTSTRAP=bootstrap-cygwin
else
    BOOTSTRAP=bootstrap
fi
$(dirname $0)/Build/tools/$BOOTSTRAP $(dirname $0)
