#! /bin/bash

echo "$1 [TARGET]"
echo
echo "Targets:"
echo "  <none>      ... automatically configure and build"
echo "  conf-clean  ... clean configuration"
echo "  clean       ... clean all build files"
if [ $(./contains-libraries) -ne 0 ]; then
	echo "  application ... create new application"
	echo "  cache       ... create initial cache (CMackeCache.txt)"
fi
echo "  help        ... print this help"
echo ""
