#! /bin/bash

CWD_SAVED=$PWD

function msg() { echo "$(basename $0): $1"; }
function debug() { echo "$(basename $0): $1" 1>&2; }

function err() {
	ret=$?
	if [ "$1" != "" ]; then echo "$(basename $0): $1" 1>&2; fi
	cd $CWD_SAVED
	if [ $ret -ne 0 ]; then exit $ret; else exit 1; fi
}

function succeed() {
	echo
	cd $CWD_SAVED
	exit 0
}
