/*
 * SyntaxSugar.hpp -- generated by SyntaxSugar.sh
 *
 * Copyright (c) 2007-2009, Frank Mertens
 *
 * See ../LICENSE for the license.
 */
inline static NODE CHOICE(NODE choice0, NODE choice1) {
	return new OrNode(choice0, choice1);
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2) {
	return new OrNode(choice0, new OrNode(choice1, choice2));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, choice3)));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, choice4))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, choice5)))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, choice6))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, choice7)))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, choice8))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, choice9)))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, choice10))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, choice11)))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, choice12))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, choice13)))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, choice14))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, choice15)))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, choice16))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, choice17)))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, choice18))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, choice19)))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, choice20))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, choice21)))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, choice22))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, choice23)))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, choice24))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, choice25)))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25, NODE choice26) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, new OrNode(choice25, choice26))))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25, NODE choice26, NODE choice27) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, new OrNode(choice25, new OrNode(choice26, choice27)))))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25, NODE choice26, NODE choice27, NODE choice28) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, new OrNode(choice25, new OrNode(choice26, new OrNode(choice27, choice28))))))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25, NODE choice26, NODE choice27, NODE choice28, NODE choice29) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, new OrNode(choice25, new OrNode(choice26, new OrNode(choice27, new OrNode(choice28, choice29)))))))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25, NODE choice26, NODE choice27, NODE choice28, NODE choice29, NODE choice30) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, new OrNode(choice25, new OrNode(choice26, new OrNode(choice27, new OrNode(choice28, new OrNode(choice29, choice30))))))))))))))))))))))))))))));
}
inline static NODE CHOICE(NODE choice0, NODE choice1, NODE choice2, NODE choice3, NODE choice4, NODE choice5, NODE choice6, NODE choice7, NODE choice8, NODE choice9, NODE choice10, NODE choice11, NODE choice12, NODE choice13, NODE choice14, NODE choice15, NODE choice16, NODE choice17, NODE choice18, NODE choice19, NODE choice20, NODE choice21, NODE choice22, NODE choice23, NODE choice24, NODE choice25, NODE choice26, NODE choice27, NODE choice28, NODE choice29, NODE choice30, NODE choice31) {
	return new OrNode(choice0, new OrNode(choice1, new OrNode(choice2, new OrNode(choice3, new OrNode(choice4, new OrNode(choice5, new OrNode(choice6, new OrNode(choice7, new OrNode(choice8, new OrNode(choice9, new OrNode(choice10, new OrNode(choice11, new OrNode(choice12, new OrNode(choice13, new OrNode(choice14, new OrNode(choice15, new OrNode(choice16, new OrNode(choice17, new OrNode(choice18, new OrNode(choice19, new OrNode(choice20, new OrNode(choice21, new OrNode(choice22, new OrNode(choice23, new OrNode(choice24, new OrNode(choice25, new OrNode(choice26, new OrNode(choice27, new OrNode(choice28, new OrNode(choice29, new OrNode(choice30, choice31)))))))))))))))))))))))))))))));
}
inline static NODE GLUE(NODE node0, NODE node1) {
	node0->next_ = node1;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2) {
	node0->next_ = node1;
	node1->next_ = node2;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25, NODE node26) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	node25->next_ = node26;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25, NODE node26, NODE node27) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	node25->next_ = node26;
	node26->next_ = node27;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25, NODE node26, NODE node27, NODE node28) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	node25->next_ = node26;
	node26->next_ = node27;
	node27->next_ = node28;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25, NODE node26, NODE node27, NODE node28, NODE node29) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	node25->next_ = node26;
	node26->next_ = node27;
	node27->next_ = node28;
	node28->next_ = node29;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25, NODE node26, NODE node27, NODE node28, NODE node29, NODE node30) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	node25->next_ = node26;
	node26->next_ = node27;
	node27->next_ = node28;
	node28->next_ = node29;
	node29->next_ = node30;
	return node0;
}
inline static NODE GLUE(NODE node0, NODE node1, NODE node2, NODE node3, NODE node4, NODE node5, NODE node6, NODE node7, NODE node8, NODE node9, NODE node10, NODE node11, NODE node12, NODE node13, NODE node14, NODE node15, NODE node16, NODE node17, NODE node18, NODE node19, NODE node20, NODE node21, NODE node22, NODE node23, NODE node24, NODE node25, NODE node26, NODE node27, NODE node28, NODE node29, NODE node30, NODE node31) {
	node0->next_ = node1;
	node1->next_ = node2;
	node2->next_ = node3;
	node3->next_ = node4;
	node4->next_ = node5;
	node5->next_ = node6;
	node6->next_ = node7;
	node7->next_ = node8;
	node8->next_ = node9;
	node9->next_ = node10;
	node10->next_ = node11;
	node11->next_ = node12;
	node12->next_ = node13;
	node13->next_ = node14;
	node14->next_ = node15;
	node15->next_ = node16;
	node16->next_ = node17;
	node17->next_ = node18;
	node18->next_ = node19;
	node19->next_ = node20;
	node20->next_ = node21;
	node21->next_ = node22;
	node22->next_ = node23;
	node23->next_ = node24;
	node24->next_ = node25;
	node25->next_ = node26;
	node26->next_ = node27;
	node27->next_ = node28;
	node28->next_ = node29;
	node29->next_ = node30;
	node30->next_ = node31;
	return node0;
}
